import { ThemeConfig, ThemeKey } from '../types';

export const THEMES: Record<ThemeKey, ThemeConfig> = {
  'clean-minimal': {
    id: 'clean-minimal',
    name: 'คลีนมินิมอล & สเลท (Clean Slate)',
    nameEn: 'Clean Slate Minimal',
    description: 'โทนขาวสว่างตัดด้วยสเลทดำเข้ม เรียบง่าย สะอาดตา คมชัดทุกมุมมอง สไตล์ Modern Studio',
    badge: '✨ สว่าง สะอาด คลีนมินิมอล (ยอดนิยม)',
    isDark: false,
    bgMain: 'bg-[#f8fafc] text-slate-900',
    bgCard: 'bg-white border border-slate-200/90 shadow-sm shadow-slate-200/50',
    bgCardHover: 'hover:border-slate-300 hover:shadow-md transition-all',
    borderSubtle: 'border-slate-200',
    borderActive: 'border-slate-900',
    primary: 'bg-slate-900 text-white hover:bg-slate-800 font-semibold shadow-xs',
    primaryHover: 'hover:bg-slate-800',
    primaryLight: 'bg-slate-100 text-slate-900 border border-slate-200',
    primaryText: 'text-slate-900',
    accent: 'from-slate-900 to-slate-800',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-slate-200/90 shadow-xs',
    tabActiveBg: 'bg-slate-900 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#0f172a',
    inputBg: 'bg-slate-50 border-slate-200 text-slate-900 placeholder:text-slate-400 focus:bg-white focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10',
    textHeading: 'text-slate-900',
    textMuted: 'text-slate-500',
    cardInnerBg: 'bg-slate-50/80 border border-slate-100',
  },
  'warm-amber-gold': {
    id: 'warm-amber-gold',
    name: 'แชมเปญโกลด์ & ครีมไอวอรี่ (Champagne Gold)',
    nameEn: 'Champagne Gold & Ivory',
    description: 'โทนขาวครีมไอวอรี่ ผสานประกายทองคำแชมเปญ หรูหรา อบอุ่น สไตล์ Master Barber & High-End Salon',
    badge: '👑 หรูหรา อบอุ่นระดับพรีเมียม',
    isDark: false,
    bgMain: 'bg-[#faf8f5] text-amber-950',
    bgCard: 'bg-white border border-amber-200/70 shadow-sm shadow-amber-100/40',
    bgCardHover: 'hover:border-amber-300 hover:shadow-md transition-all',
    borderSubtle: 'border-amber-200/60',
    borderActive: 'border-amber-600',
    primary: 'bg-amber-600 text-white hover:bg-amber-500 font-semibold shadow-xs',
    primaryHover: 'hover:bg-amber-500',
    primaryLight: 'bg-amber-50 text-amber-900 border border-amber-200',
    primaryText: 'text-amber-700',
    accent: 'from-amber-500 to-amber-600',
    headerBg: 'bg-[#fffdfa]/95 backdrop-blur-md border-b border-amber-200/80 shadow-xs',
    tabActiveBg: 'bg-amber-600 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#d97706',
    inputBg: 'bg-amber-50/50 border-amber-200/80 text-amber-950 placeholder:text-amber-500 focus:bg-white focus:border-amber-600 focus:ring-2 focus:ring-amber-500/10',
    textHeading: 'text-amber-950',
    textMuted: 'text-amber-800/70',
    cardInnerBg: 'bg-amber-50/40 border border-amber-100',
  },
  'royal-sapphire': {
    id: 'royal-sapphire',
    name: 'รอยัลแซฟไฟร์ บลู (Royal Sapphire Blue)',
    nameEn: 'Royal Sapphire Blue',
    description: 'โทนขาวไอซ์บลู สดใส มั่นใจ คมชัด โดดเด่นด้วยสีน้ำเงินแซฟไฟร์ สไตล์สปอร์ตบาร์เบอร์และโมเดิร์นคลาสสิก',
    badge: '💎 โมเดิร์น คมชัด น่าเชื่อถือ',
    isDark: false,
    bgMain: 'bg-[#f0f7ff] text-slate-900',
    bgCard: 'bg-white border border-sky-200/70 shadow-sm shadow-sky-100/40',
    bgCardHover: 'hover:border-sky-300 hover:shadow-md transition-all',
    borderSubtle: 'border-sky-200/70',
    borderActive: 'border-sky-600',
    primary: 'bg-sky-600 text-white hover:bg-sky-500 font-semibold shadow-xs',
    primaryHover: 'hover:bg-sky-500',
    primaryLight: 'bg-sky-50 text-sky-900 border border-sky-200',
    primaryText: 'text-sky-600',
    accent: 'from-sky-500 to-blue-600',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-sky-200/80 shadow-xs',
    tabActiveBg: 'bg-sky-600 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#0284c7',
    inputBg: 'bg-sky-50/40 border-sky-200 text-slate-900 placeholder:text-slate-400 focus:bg-white focus:border-sky-600 focus:ring-2 focus:ring-sky-500/10',
    textHeading: 'text-slate-900',
    textMuted: 'text-slate-500',
    cardInnerBg: 'bg-sky-50/40 border border-sky-100',
  },
  'nordic-sage': {
    id: 'nordic-sage',
    name: 'นอร์ดิกเซจ & เอิร์ธมินต์ (Nordic Sage & Mint)',
    nameEn: 'Nordic Sage & Mint',
    description: 'โทนขาวเนเชอรัล ผสานความสดชื่นของสีเขียวเซจและมินต์ ให้ความรู้สึกผ่อนคลาย สะอาด สไตล์ Organic Hair Studio',
    badge: '🌿 ผ่อนคลาย สดชื่น สไตล์สแกนดิเนเวีย',
    isDark: false,
    bgMain: 'bg-[#f4f9f6] text-emerald-950',
    bgCard: 'bg-white border border-emerald-200/70 shadow-sm shadow-emerald-100/40',
    bgCardHover: 'hover:border-emerald-300 hover:shadow-md transition-all',
    borderSubtle: 'border-emerald-200/70',
    borderActive: 'border-emerald-600',
    primary: 'bg-emerald-600 text-white hover:bg-emerald-500 font-semibold shadow-xs',
    primaryHover: 'hover:bg-emerald-500',
    primaryLight: 'bg-emerald-50 text-emerald-900 border border-emerald-200',
    primaryText: 'text-emerald-700',
    accent: 'from-emerald-500 to-teal-600',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-emerald-200/80 shadow-xs',
    tabActiveBg: 'bg-emerald-600 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#059669',
    inputBg: 'bg-emerald-50/40 border-emerald-200 text-emerald-950 placeholder:text-emerald-600/50 focus:bg-white focus:border-emerald-600 focus:ring-2 focus:ring-emerald-500/10',
    textHeading: 'text-emerald-950',
    textMuted: 'text-emerald-800/70',
    cardInnerBg: 'bg-emerald-50/40 border border-emerald-100',
  },
  'rose-elegance': {
    id: 'rose-elegance',
    name: 'โรสเอเลแกนซ์ & พิงค์บลัช (Rose Elegance & Coral)',
    nameEn: 'Rose Elegance & Coral',
    description: 'โทนขาวพิงค์ไอวอรี่ แซมความหรูหราของสีกุหลาบ Rose Coral เหมาะสำหรับร้านซาลอนและบาร์เบอร์ระดับไฮเอนด์',
    badge: '🌸 สง่างาม อ่อนโยน พรีเมียมซาลอน',
    isDark: false,
    bgMain: 'bg-[#fff7f8] text-rose-950',
    bgCard: 'bg-white border border-rose-200/70 shadow-sm shadow-rose-100/40',
    bgCardHover: 'hover:border-rose-300 hover:shadow-md transition-all',
    borderSubtle: 'border-rose-200/70',
    borderActive: 'border-rose-500',
    primary: 'bg-rose-600 text-white hover:bg-rose-500 font-semibold shadow-xs',
    primaryHover: 'hover:bg-rose-500',
    primaryLight: 'bg-rose-50 text-rose-900 border border-rose-200',
    primaryText: 'text-rose-600',
    accent: 'from-rose-500 to-pink-600',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-rose-200/80 shadow-xs',
    tabActiveBg: 'bg-rose-600 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#e11d48',
    inputBg: 'bg-rose-50/40 border-rose-200 text-rose-950 placeholder:text-rose-400 focus:bg-white focus:border-rose-500 focus:ring-2 focus:ring-rose-500/10',
    textHeading: 'text-rose-950',
    textMuted: 'text-rose-800/70',
    cardInnerBg: 'bg-rose-50/40 border border-rose-100',
  },
  'vintage-terracotta': {
    id: 'vintage-terracotta',
    name: 'วินเทจบาร์เบอร์ & เทอราคอตต้า (Vintage Terracotta)',
    nameEn: 'Vintage Terracotta',
    description: 'โทนขาวอบอุ่นสไตล์วินเทจ ตัดด้วยสีส้มอิฐเผา Terracotta ให้กลิ่นอาย Classic American Barber Shop ดั้งเดิม',
    badge: '💈 วินเทจบาร์เบอร์ดั้งเดิม คลาสสิก',
    isDark: false,
    bgMain: 'bg-[#fef9f5] text-orange-950',
    bgCard: 'bg-white border border-orange-200/70 shadow-sm shadow-orange-100/40',
    bgCardHover: 'hover:border-orange-300 hover:shadow-md transition-all',
    borderSubtle: 'border-orange-200/70',
    borderActive: 'border-orange-600',
    primary: 'bg-orange-600 text-white hover:bg-orange-500 font-semibold shadow-xs',
    primaryHover: 'hover:bg-orange-500',
    primaryLight: 'bg-orange-50 text-orange-900 border border-orange-200',
    primaryText: 'text-orange-600',
    accent: 'from-orange-500 to-amber-600',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-orange-200/80 shadow-xs',
    tabActiveBg: 'bg-orange-600 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#ea580c',
    inputBg: 'bg-orange-50/40 border-orange-200 text-orange-950 placeholder:text-orange-400 focus:bg-white focus:border-orange-600 focus:ring-2 focus:ring-orange-500/10',
    textHeading: 'text-orange-950',
    textMuted: 'text-orange-800/70',
    cardInnerBg: 'bg-orange-50/40 border border-orange-100',
  },
  'violet-luxury': {
    id: 'violet-luxury',
    name: 'รอยัลไวโอเล็ต & อเมทิสต์ (Royal Violet Luxury)',
    nameEn: 'Royal Violet Luxury',
    description: 'โทนขาวลาเวนเดอร์ ผสานความสง่างามของสีม่วงอเมทิสต์ ลุคแฟชั่นระดับสูง แปลกใหม่ ทรงคุณค่า',
    badge: '🔮 แฟชั่นลักชัวรี โดดเด่น ทันสมัย',
    isDark: false,
    bgMain: 'bg-[#faf5ff] text-purple-950',
    bgCard: 'bg-white border border-purple-200/70 shadow-sm shadow-purple-100/40',
    bgCardHover: 'hover:border-purple-300 hover:shadow-md transition-all',
    borderSubtle: 'border-purple-200/70',
    borderActive: 'border-purple-600',
    primary: 'bg-purple-600 text-white hover:bg-purple-500 font-semibold shadow-xs',
    primaryHover: 'hover:bg-purple-500',
    primaryLight: 'bg-purple-50 text-purple-900 border border-purple-200',
    primaryText: 'text-purple-600',
    accent: 'from-purple-500 to-indigo-600',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-purple-200/80 shadow-xs',
    tabActiveBg: 'bg-purple-600 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#9333ea',
    inputBg: 'bg-purple-50/40 border-purple-200 text-purple-950 placeholder:text-purple-400 focus:bg-white focus:border-purple-600 focus:ring-2 focus:ring-purple-500/10',
    textHeading: 'text-purple-950',
    textMuted: 'text-purple-800/70',
    cardInnerBg: 'bg-purple-50/40 border border-purple-100',
  },
  'japanese-zen': {
    id: 'japanese-zen',
    name: 'เซน มูจิ & เอิร์ธโทน (Zen Sandstone & Earth)',
    nameEn: 'Zen Sandstone & Earth',
    description: 'โทนขาวทรายและวู้ดเธิร์ด อบอุ่น เรียบง่าย สบายตาสไตล์ Minimalist Japanese & Muji House',
    badge: '🎋 สบายตา เรียบง่าย มินิมอล',
    isDark: false,
    bgMain: 'bg-[#fcfaf7] text-stone-900',
    bgCard: 'bg-white border border-stone-200/90 shadow-sm shadow-stone-200/40',
    bgCardHover: 'hover:border-stone-300 hover:shadow-md transition-all',
    borderSubtle: 'border-stone-200',
    borderActive: 'border-stone-800',
    primary: 'bg-stone-800 text-white hover:bg-stone-700 font-semibold shadow-xs',
    primaryHover: 'hover:bg-stone-700',
    primaryLight: 'bg-stone-100 text-stone-900 border border-stone-200',
    primaryText: 'text-stone-700',
    accent: 'from-stone-700 to-stone-900',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-stone-200/80 shadow-xs',
    tabActiveBg: 'bg-stone-800 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#57534e',
    inputBg: 'bg-stone-50 border-stone-200 text-stone-900 placeholder:text-stone-400 focus:bg-white focus:border-stone-800 focus:ring-2 focus:ring-stone-800/10',
    textHeading: 'text-stone-900',
    textMuted: 'text-stone-500',
    cardInnerBg: 'bg-stone-50/80 border border-stone-100',
  },

  // Legacy mappings - redirected to clean white themes
  'professional-polish': {
    id: 'professional-polish',
    name: 'คลีนมินิมอล & สเลท (Clean Slate)',
    nameEn: 'Clean Slate Minimal',
    description: 'โทนขาวสว่างตัดด้วยสเลทดำเข้ม เรียบง่าย สะอาดตา คมชัดทุกมุมมอง สไตล์ Modern Studio',
    badge: '✨ สว่าง สะอาด คลีนมินิมอล (ยอดนิยม)',
    isDark: false,
    bgMain: 'bg-[#f8fafc] text-slate-900',
    bgCard: 'bg-white border border-slate-200/90 shadow-sm shadow-slate-200/50',
    bgCardHover: 'hover:border-slate-300 hover:shadow-md transition-all',
    borderSubtle: 'border-slate-200',
    borderActive: 'border-slate-900',
    primary: 'bg-slate-900 text-white hover:bg-slate-800 font-semibold shadow-xs',
    primaryHover: 'hover:bg-slate-800',
    primaryLight: 'bg-slate-100 text-slate-900 border border-slate-200',
    primaryText: 'text-slate-900',
    accent: 'from-slate-900 to-slate-800',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-slate-200/90 shadow-xs',
    tabActiveBg: 'bg-slate-900 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#0f172a',
    inputBg: 'bg-slate-50 border-slate-200 text-slate-900 placeholder:text-slate-400 focus:bg-white focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10',
    textHeading: 'text-slate-900',
    textMuted: 'text-slate-500',
    cardInnerBg: 'bg-slate-50/80 border border-slate-100',
  },
  'luxury-gold': {
    id: 'luxury-gold',
    name: 'แชมเปญโกลด์ & ครีมไอวอรี่ (Champagne Gold)',
    nameEn: 'Champagne Gold & Ivory',
    description: 'โทนขาวครีมไอวอรี่ ผสานประกายทองคำแชมเปญ หรูหรา อบอุ่น สไตล์ Master Barber & High-End Salon',
    badge: '👑 หรูหรา อบอุ่นระดับพรีเมียม',
    isDark: false,
    bgMain: 'bg-[#faf8f5] text-amber-950',
    bgCard: 'bg-white border border-amber-200/70 shadow-sm shadow-amber-100/40',
    bgCardHover: 'hover:border-amber-300 hover:shadow-md transition-all',
    borderSubtle: 'border-amber-200/60',
    borderActive: 'border-amber-600',
    primary: 'bg-amber-600 text-white hover:bg-amber-500 font-semibold shadow-xs',
    primaryHover: 'hover:bg-amber-500',
    primaryLight: 'bg-amber-50 text-amber-900 border border-amber-200',
    primaryText: 'text-amber-700',
    accent: 'from-amber-500 to-amber-600',
    headerBg: 'bg-[#fffdfa]/95 backdrop-blur-md border-b border-amber-200/80 shadow-xs',
    tabActiveBg: 'bg-amber-600 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#d97706',
    inputBg: 'bg-amber-50/50 border-amber-200/80 text-amber-950 placeholder:text-amber-500 focus:bg-white focus:border-amber-600 focus:ring-2 focus:ring-amber-500/10',
    textHeading: 'text-amber-950',
    textMuted: 'text-amber-800/70',
    cardInnerBg: 'bg-amber-50/40 border border-amber-100',
  },
  'charcoal-classic': {
    id: 'charcoal-classic',
    name: 'คลีนมินิมอล & สเลท (Clean Slate)',
    nameEn: 'Clean Slate Minimal',
    description: 'โทนขาวสว่างตัดด้วยสเลทดำเข้ม เรียบง่าย สะอาดตา คมชัดทุกมุมมอง สไตล์ Modern Studio',
    badge: '✨ สว่าง สะอาด คลีนมินิมอล (ยอดนิยม)',
    isDark: false,
    bgMain: 'bg-[#f8fafc] text-slate-900',
    bgCard: 'bg-white border border-slate-200/90 shadow-sm shadow-slate-200/50',
    bgCardHover: 'hover:border-slate-300 hover:shadow-md transition-all',
    borderSubtle: 'border-slate-200',
    borderActive: 'border-slate-900',
    primary: 'bg-slate-900 text-white hover:bg-slate-800 font-semibold shadow-xs',
    primaryHover: 'hover:bg-slate-800',
    primaryLight: 'bg-slate-100 text-slate-900 border border-slate-200',
    primaryText: 'text-slate-900',
    accent: 'from-slate-900 to-slate-800',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-slate-200/90 shadow-xs',
    tabActiveBg: 'bg-slate-900 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#0f172a',
    inputBg: 'bg-slate-50 border-slate-200 text-slate-900 placeholder:text-slate-400 focus:bg-white focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10',
    textHeading: 'text-slate-900',
    textMuted: 'text-slate-500',
    cardInnerBg: 'bg-slate-50/80 border border-slate-100',
  },
  'modern-sage': {
    id: 'modern-sage',
    name: 'นอร์ดิกเซจ & เอิร์ธมินต์ (Nordic Sage & Mint)',
    nameEn: 'Nordic Sage & Mint',
    description: 'โทนขาวเนเชอรัล ผสานความสดชื่นของสีเขียวเซจและมินต์ ให้ความรู้สึกผ่อนคลาย สะอาด สไตล์ Organic Hair Studio',
    badge: '🌿 ผ่อนคลาย สดชื่น สไตล์สแกนดิเนเวีย',
    isDark: false,
    bgMain: 'bg-[#f4f9f6] text-emerald-950',
    bgCard: 'bg-white border border-emerald-200/70 shadow-sm shadow-emerald-100/40',
    bgCardHover: 'hover:border-emerald-300 hover:shadow-md transition-all',
    borderSubtle: 'border-emerald-200/70',
    borderActive: 'border-emerald-600',
    primary: 'bg-emerald-600 text-white hover:bg-emerald-500 font-semibold shadow-xs',
    primaryHover: 'hover:bg-emerald-500',
    primaryLight: 'bg-emerald-50 text-emerald-900 border border-emerald-200',
    primaryText: 'text-emerald-700',
    accent: 'from-emerald-500 to-teal-600',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-emerald-200/80 shadow-xs',
    tabActiveBg: 'bg-emerald-600 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#059669',
    inputBg: 'bg-emerald-50/40 border-emerald-200 text-emerald-950 placeholder:text-emerald-600/50 focus:bg-white focus:border-emerald-600 focus:ring-2 focus:ring-emerald-500/10',
    textHeading: 'text-emerald-950',
    textMuted: 'text-emerald-800/70',
    cardInnerBg: 'bg-emerald-50/40 border border-emerald-100',
  },
  'midnight-indigo': {
    id: 'midnight-indigo',
    name: 'รอยัลแซฟไฟร์ บลู (Royal Sapphire Blue)',
    nameEn: 'Royal Sapphire Blue',
    description: 'โทนขาวไอซ์บลู สดใส มั่นใจ คมชัด โดดเด่นด้วยสีน้ำเงินแซฟไฟร์ สไตล์สปอร์ตบาร์เบอร์และโมเดิร์นคลาสสิก',
    badge: '💎 โมเดิร์น คมชัด น่าเชื่อถือ',
    isDark: false,
    bgMain: 'bg-[#f0f7ff] text-slate-900',
    bgCard: 'bg-white border border-sky-200/70 shadow-sm shadow-sky-100/40',
    bgCardHover: 'hover:border-sky-300 hover:shadow-md transition-all',
    borderSubtle: 'border-sky-200/70',
    borderActive: 'border-sky-600',
    primary: 'bg-sky-600 text-white hover:bg-sky-500 font-semibold shadow-xs',
    primaryHover: 'hover:bg-sky-500',
    primaryLight: 'bg-sky-50 text-sky-900 border border-sky-200',
    primaryText: 'text-sky-600',
    accent: 'from-sky-500 to-blue-600',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-sky-200/80 shadow-xs',
    tabActiveBg: 'bg-sky-600 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#0284c7',
    inputBg: 'bg-sky-50/40 border-sky-200 text-slate-900 placeholder:text-slate-400 focus:bg-white focus:border-sky-600 focus:ring-2 focus:ring-sky-500/10',
    textHeading: 'text-slate-900',
    textMuted: 'text-slate-500',
    cardInnerBg: 'bg-sky-50/40 border border-sky-100',
  },
  'warm-amber': {
    id: 'warm-amber',
    name: 'วินเทจบาร์เบอร์ & เทอราคอตต้า (Vintage Terracotta)',
    nameEn: 'Vintage Terracotta',
    description: 'โทนขาวอบอุ่นสไตล์วินเทจ ตัดด้วยสีส้มอิฐเผา Terracotta ให้กลิ่นอาย Classic American Barber Shop ดั้งเดิม',
    badge: '💈 วินเทจบาร์เบอร์ดั้งเดิม คลาสสิก',
    isDark: false,
    bgMain: 'bg-[#fef9f5] text-orange-950',
    bgCard: 'bg-white border border-orange-200/70 shadow-sm shadow-orange-100/40',
    bgCardHover: 'hover:border-orange-300 hover:shadow-md transition-all',
    borderSubtle: 'border-orange-200/70',
    borderActive: 'border-orange-600',
    primary: 'bg-orange-600 text-white hover:bg-orange-500 font-semibold shadow-xs',
    primaryHover: 'hover:bg-orange-500',
    primaryLight: 'bg-orange-50 text-orange-900 border border-orange-200',
    primaryText: 'text-orange-600',
    accent: 'from-orange-500 to-amber-600',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-orange-200/80 shadow-xs',
    tabActiveBg: 'bg-orange-600 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#ea580c',
    inputBg: 'bg-orange-50/40 border-orange-200 text-orange-950 placeholder:text-orange-400 focus:bg-white focus:border-orange-600 focus:ring-2 focus:ring-orange-500/10',
    textHeading: 'text-orange-950',
    textMuted: 'text-orange-800/70',
    cardInnerBg: 'bg-orange-50/40 border border-orange-100',
  },
  'ruby-luxury': {
    id: 'ruby-luxury',
    name: 'โรสเอเลแกนซ์ & พิงค์บลัช (Rose Elegance & Coral)',
    nameEn: 'Rose Elegance & Coral',
    description: 'โทนขาวพิงค์ไอวอรี่ แซมความหรูหราของสีกุหลาบ Rose Coral เหมาะสำหรับร้านซาลอนและบาร์เบอร์ระดับไฮเอนด์',
    badge: '🌸 สง่างาม อ่อนโยน พรีเมียมซาลอน',
    isDark: false,
    bgMain: 'bg-[#fff7f8] text-rose-950',
    bgCard: 'bg-white border border-rose-200/70 shadow-sm shadow-rose-100/40',
    bgCardHover: 'hover:border-rose-300 hover:shadow-md transition-all',
    borderSubtle: 'border-rose-200/70',
    borderActive: 'border-rose-500',
    primary: 'bg-rose-600 text-white hover:bg-rose-500 font-semibold shadow-xs',
    primaryHover: 'hover:bg-rose-500',
    primaryLight: 'bg-rose-50 text-rose-900 border border-rose-200',
    primaryText: 'text-rose-600',
    accent: 'from-rose-500 to-pink-600',
    headerBg: 'bg-white/95 backdrop-blur-md border-b border-rose-200/80 shadow-xs',
    tabActiveBg: 'bg-rose-600 text-white font-semibold shadow-sm',
    tabActiveText: 'text-white font-semibold',
    colorSwatch: '#e11d48',
    inputBg: 'bg-rose-50/40 border-rose-200 text-rose-950 placeholder:text-rose-400 focus:bg-white focus:border-rose-500 focus:ring-2 focus:ring-rose-500/10',
    textHeading: 'text-rose-950',
    textMuted: 'text-rose-800/70',
    cardInnerBg: 'bg-rose-50/40 border border-rose-100',
  },
};
